### ISSUE TITLE
Are you planing to integrate yes cart to idempier crm?

### ISSUE THREAD

**Issue by topstarnetwork** [inspire-software/yes-cart#34]
Hello,
Are you planing to integrate yes cart to idempier crm?

**Comment by inspire-software** [comment]
Hi,

In short no, we do not provide integrations in our core core. Reason being is that there are so much choice in what you can use in terms of CRM and ERP systems it is impractical to provide integrations of that sort, nor it is possible to maintain this code afterwards.

However YC is build as SOA (Service Oriented Architecture) and we have a comprehensive Import/Export service facility via CSV. Therefore any 3rd party systems can be easily integrated. 

Most of YC users find auto import service facility sufficient. CSV file feeds are imported via service on cron schedule into YC. 

If however you require more real-time integrations we have YC users who would change implementations of some of the out of the box services in order to have direct calls (e.g. PriceService implementation to fetch prices from SAP). It is a easy as providing your own implementation for service Spring bean, literally!

YC is very flexible and easy to adapt to your needs, however if you need some detail designs of how to implement certain integration you can always contact us on http://www.yes-cart.org/#contact and make use of our professional services.

Hope this helps,
YC team

**Comment by topstarnetwork** [comment]
Thanks I will contacct you directly on your website for any eventual custom development code,
regards, Heather
