### ISSUE TITLE
Product Rating

### ISSUE THREAD

**Issue by Alessandro77** [inspire-software/yes-cart#35]
Hi guys, are you planning to add product rating to yes-cart?
i also see the multiple sku support, but how about variations like size in clothing?

**Comment by inspire-software** [comment]
Hi,

You have two questions here:

1. product rating

This is very specific to the project because some people just want a manually manage star rating (effectively adding an attribute to product and then creatively display it as stars or bars or whatever). Others have full blown integration to Trustpilot, Bazaarvoice, Google to name a few. Each of the "rating" third party has different API's (not to mention that some API's require credentials) so it is impractical have those in core, since it is easy integration. Most of these can be integrated via JavaScript API (essentially place a piece of JS in page, which you can do using the content framework built-in to YC).

So to answer, will we have it in core - no, but there is a good foundation to integrate any rating system you like. In our experience these take no long than 3-5days to do, and most of that time is discussing on how exactly this needs to be integrated.

2. multiple sku support, but how about variations like size in clothing

This is already built in. Multiple SKU are in fact variations, it is the same thing. Specific SKU (stock keeping unit) is a variant with specific parameter such as size. So when modelling products, you can create product "T-shirt" and then create SKU(s) "T-shirt S", "T-shirt M", "T-shirt L" etc. Default theme just renders those on product details page. For example use the demo to see how mutisku products behave: http://demo.yes-cart.org/yes-shop/tag/multisku 

On demo it may not look very pretty but there is nothing that a bit of css and creative JavaScript cannot do :).

Regards,
YC Team

**Comment by Alessandro77** [comment]
Thx, i like yes-cart ! so, if i need to use T-shirt S Blue, T-shirt S Red, T-shirt M Blue, T-shirt M Red ... maybe i must create 2 products, but how can i "link" togheter? Also : if i need to hire you for implementation, it's possible ? leave me your mail or phone n. :)

**Comment by inspire-software** [comment]
Hi,

The product modelling depends on how you want to display the product. The basic setup for your case is to use one product T Shirt, and then a SKU for each size+color pair. Some people choose to group by size in such case you have product for each size (Say T-Shirt S) and then SKU for every colour. There is no wrong here it all depends on how you want it displayed on the fronted.

We do have professional services as well where you can hire us on time & material basis. We can do many things from providing analysis and recommend best approaches, to implementing modules for you.

If you want to request for professional services please use our contact form: http://www.yes-cart.org/#contact

Regards,
YC team

P.S. I am going to close this ticket (you the contact form for all questions you may have)
