### ISSUE TITLE
dataSource - jdbc/yesjndi is not bound

### ISSUE THREAD

**Issue by Mohankonnect** [inspire-software/yes-cart#48]
Am using mysql database  .. when i run yes-shop  in tomcat server its
showing the following error.

ERROR o.s.w.c.ContextLoader:350 - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'dataSource' defined in class path resource
[core-persistence.xml]: Invocation of init method failed; nested exception
is javax.naming.NameNotFoundException: Name [jdbc/yesjndi] is not bound in
this Context. Unable to find [jdbc].

 I am having mysql in separate server.  Added the host address and port number
in init_db_mysql() in yc.sh and config-db-mysql.properties file.
 Changed localhost to % in in dbinit.sql file..

But still the issue not solved. so please help to solve this issue.

Thanks in advance

**Comment by inspire-software** [comment]
There could be several reasons.

1. config-db-mysql.properties is used as maven filter, so every time you change it you need to rebuild. Make sure that you have re-built and re-deployed your webapp after you made the changes

2. You are building using wrong environment profiles. There are multiple environment specific config-db-mysql.properties. Make sure you changed the correct one.

3. You are running you tomcat inside IntellijIDEA. Sometimes when you do command line builds and then IntellijIDEA gets confused as it has its own just in time builder. So you need to run "install" from Itellij, which is exactly what is shown in this video: https://www.youtube.com/watch?v=I7QZja62WWw (start watching at 12:30 onwards)

We highly recommend that you study carefully the installation from source guide so that you have a better understanding of how this all ties together. See it here http://www.inspire-software.com/documentation/wiki/docyescart/view/3.3.x/For%20Technical%20Users/Installation/From%20source/ 

Just FYI our "demo" environment profile uses mysql so please study how this is setup: https://github.com/inspire-software/yes-cart/tree/master/env/maven/demo

Reference mvn command is: 
`mvn clean install -PbuildDemo,mysql,ftEmbededLucene,paymentAll,pricerules -DskipTests=true`
