### ISSUE TITLE
API /cart need to be expanded

### ISSUE THREAD

**Issue by iazarny** [inspire-software/yes-cart#65]
The item hash not name(s)

{
  "items": [
    {
      "productSkuCode": "NX-EF1ET-009",
      "quantity": 1,
      "supplierCode": "Main",
      "deliveryGroup": null,
      "itemGroup": null,
      "price": 1426.42,
      "salePrice": 1426.42,
      "listPrice": 1426.42,
      "netPrice": 1188.68,
      "grossPrice": 1426.42,
      "taxRate": 20.00,
      "taxCode": "VAT",
      "taxExclusiveOfPrice": false,
      "notSoldSeparately": false,
      "configurable": false,
      "gift": false,
      "promoApplied": false,
      "fixedPrice": false,
      "appliedPromo": null,
      "unitPricing": {
        "currency": "EUR",
        "symbol": "€",
        "symbolPosition": "before",
        "quantity": 1,
        "priceUponRequest": false,
        "priceOnOffer": false,
        "regularPrice": 1426.42,
        "salePrice": null,
        "taxInfoEnabled": true,
        "taxInfoUseNet": false,
        "taxInfoShowAmount": true,
        "priceTaxCode": "VAT",
        "priceTaxRate": 20.00,
        "priceTaxExclusive": false,
        "priceTax": 237.74,
        "discount": null
      },
      "totalPricing": {
        "currency": "EUR",
        "symbol": "€",
        "symbolPosition": "before",
        "quantity": 1,
        "priceUponRequest": false,
        "priceOnOffer": false,
        "regularPrice": 1426.42,
        "salePrice": null,
        "taxInfoEnabled": true,
        "taxInfoUseNet": false,
        "taxInfoShowAmount": true,
        "priceTaxCode": "VAT",
        "priceTaxRate": 20.00,
        "priceTaxExclusive": false,
        "priceTax": 237.74,
        "discount": null
      }
    }
  ],

**Comment by iazarny** [comment]
So need name(s) and default sku image

**Comment by inspire-software** [comment]
Cart API is fully decoupled from the PIM. This is so that cart can be used as a "calculator" for headless mode whereby you only need inventory by SKU code and price list by SKU code. Therefore cart API is very lightweight and does not have the mentioned details such as name and image. To have "rich" product information use POST /skus/list API ( https://demo.yes-cart.org/api/rest/swagger-ui.html#/search/viewSkusUsingPOST ) using SKU codes and supplier from cart items.

**Comment by iazarny** [comment]
Lead to N+1 calls .  Just to compare call vs two additional fields. Ok . np

**Comment by inspire-software** [comment]
It is a little bit more than just 2 fields because that field represents a image file which will need to be somewhere and if this is just a "cart calculator" there would be no place where to get the reference for that file etc, which would mean "coupling in" some of the PIM functionality for the image retrieval logic. 

As for name it is locale aware and therefore it is also not a single field and will change depending the the locale selected on the site (e.g. multi-ligual sites). If we record the name in cart item then when a customer changes site's language cart recalculation would need to happen to reset those names which is a redundant process. Also at this point if it is just a calculation and that name was just "pushed in" via API then there is no means to find that name for different locale, making that logic overtly complex.
